import everythingai from "./cuterobot.png";
import praivatesearch from "./praivatesearch.png";
import whatagityear from "./whatagityear.png";
import qdurllm from "./qdurllm.png";
import pokemonbot from "./pokemons.jpg";
import sentrev from "./sentrev.png";
import proteinviz from "./protein.png";
import proteinesm from "./protein.png";
import greenfitai from "./greenfit.jpg";
import biomedpapers from "./pubmed.png";
import amplipiper from "./amplipiper.png";
import booksmixer from "./booksmixer.png";
import supaseqs from "./supaseqs.png";
import word2html from "./html.png";
import tinysd from "./sd.jpg";
import pitchgen from "./pitchgen.png";
export { everythingai, whatagityear, sentrev, praivatesearch, qdurllm, proteinviz, proteinesm, greenfitai, pokemonbot, biomedpapers, amplipiper, booksmixer, supaseqs, word2html, tinysd, pitchgen, };
