import { everythingai, praivatesearch, whatagityear, qdurllm, pokemonbot, sentrev, proteinviz, proteinesm, greenfitai, biomedpapers, amplipiper, booksmixer, supaseqs, word2html, tinysd, pitchgen } from "./index";
export const projectArray = [
    {
        name: "Maddie AI",
        description: "Maddie AI is an advanced conversational AI assistant designed to engage in natural language interactions and assist users with a wide range of tasks. Powered by large language models and cutting-edge machine learning techniques, Maddie AI can understand context, provide informative responses, and even generate human-like text on demand.",
        image: everythingai,
        type: "Open Source",
        hostedLink: "",
        githubLink: "https://github.com/HeyMridul/Maddie-AI",
    },
    {
        name: "Pathsala",
        description: "Pathsala is an integrated platform to share books and educational resource among students, we apply this community based approach of harvesting the sense of sharing not just resources but a light if connecting knowledge",
        image: praivatesearch,
        type: "Open Source",
        hostedLink: "",
        githubLink: "https://github.com/HeyMridul/Pathsala",
    },
    {
        name: "SportsGather",
        description: "AN Innovative Platform for promoting sports",
        image: qdurllm,
        type: "Open Source",
        hostedLink: "",
        githubLink: "https://github.com/HeyMridul/SportsGather",
    },
    {
        name: "Story-Escape",
        description: "Provide better accessibility features and add more interactivity to help keep children engaged and optimise their imagination.",
        image: sentrev,
        type: "Open Source",
        hostedLink: "",
        githubLink: "https://github.com/HeyMridul/Story_Escape",
    },
    {
        name: "Cancer-Detection",
        description: "an AI-powered web app for the automatic detection of skin diseases. By using the app, users can receive automatic evaluations from the app about their skin condition.",
        image: pokemonbot,
        type: "Open Source",
        hostedLink: "",
        githubLink: "https://github.com/HeyMridul/Cancer-Detection",
    },
    // {
    //     name: "ProteinViz",
    //     description: "Your open-source alternative to AlphaFold3🚀",
    //     image: proteinviz,
    //     type: "Open Source",
    //     hostedLink: "",
    //     githubLink: "https://www.github.com/AstraBert/proteinviz",
    // },
    // {
    //     name: "GreenFit AI",
    //     description: "Find out about sustainability in your favorite sport clothing brands, in just one click!",
    //     image: greenfitai,
    //     type: "Open Source",
    //     hostedLink: "https://huggingface.co/spaces/greenfit-ai/greenfit-ai",
    //     githubLink: "https://www.github.com/greenfit-ai/greenfit-ai",
    // },
    // {
    //     name: "What a Git Year!",
    //     description: "Simple Gradio app to showcase your GitHub achievements in the past year",
    //     image: whatagityear,
    //     type: "open source",
    //     hostedLink: "https://huggingface.co/spaces/as-cle-bert/what-a-git-year",
    //     githubLink: "https://www.github.com/AstraBert/what-a-git-year",
    // },
    // {
    //     name: "BiomedicalPapersBot",
    //     description: "A Gradio bot to retrieve PubMed papers' title, doi, authors and publication date based on general search terms or on specific publication names",
    //     image: biomedpapers,
    //     type: "Open Source",
    //     hostedLink: "https://huggingface.co/spaces/as-cle-bert/BioMedicalPapersBot",
    //     githubLink: "https://www.github.com/AstraBert/BioMedicalPapersBot",
    // },
    // {
    //     name: "AmpliPiper",
    //     description: "AmpliPiper is a comprehensive workflow based on BASH scripting, Python and R for analyzing high-throughput amplicon sequencing data for multiple samples and loci. The pipeline performs various tasks, including raw read demultiplexing, filtering, consensus sequence reconstruction, species identification and phylogenetic analysis.",
    //     image: amplipiper,
    //     type: "Open Source",
    //     hostedLink: "https://www.biorxiv.org/content/10.1101/2024.12.11.628038v1",
    //     githubLink: "https://github.com/nhmvienna/AmpliPiper",
    // },
    // {
    //     name: "books-mixer-ai",
    //     description: "Mix and twist your favorite books with the power of AI!📖.",
    //     image: booksmixer,
    //     type: "Open Source",
    //     hostedLink: "https://www.booksmixerai.xyz/",
    //     githubLink: "https://github.com/AstraBert/books-mixer-ai",
    // },
    // {
    //     name: "pitchgen-bot",
    //     description: "Great pitches for great ideas: make it easy with AI!🗣️",
    //     image: pitchgen,
    //     type: "Open Source",
    //     hostedLink: "",
    //     githubLink: "https://github.com/AstraBert/pitchgen-bot",
    // },
    // {
    //     name: "SupaSeqs",
    //     description: "Basically BLAST, but written in PostgreSQL😉",
    //     image: supaseqs,
    //     type: "Open Source",
    //     hostedLink: "",
    //     githubLink: "https://github.com/AstraBert/SupaSeqs",
    // },
    // {
    //     name: "Proteins-With-ESM",
    //     description: "Predict the whole sequence and 3D structure of masked protein sequences with ESM by @evolutionaryscale",
    //     image: proteinesm,
    //     type: "Open Source",
    //     hostedLink: "https://huggingface.co/spaces/as-cle-bert/proteins-with-esm",
    //     githubLink: "https://www.github.com/AstraBert/proteins-w-esm",
    // },
    // {
    //     name: "Word-Doc-2-HTML",
    //     description: "Python Desktop application to convert Word Documents to HTML - based on mammoth-python",
    //     image: word2html,
    //     type: "Open Source",
    //     hostedLink: "https://raw.githubusercontent.com/AstraBert/Word-Doc-2-HTML/main/application/Word-Doc-2-HTML.0.0.0.exe",
    //     githubLink: "https://github.com/AstraBert/Word-Doc-2-HTML",
    // },
    // {
    //     name: "awesome-tiny-sd",
    //     description: "Tiny stable diffusion chatbot based on segmind/small-sd to generate images upon text prompts.",
    //     image: tinysd,
    //     type: "Open Source",
    //     hostedLink: "https://huggingface.co/spaces/as-cle-bert/awesome-tiny-sd",
    //     githubLink: "https://github.com/AstraBert/awesome-tiny-sd",
    // },
];
