import docker from "./docker.svg";
import postgresssql from "./elephant.png";
import git from "./Git-Icon-1788C.svg";
import scikitlearn from "./scikit-learn-logo-small.png";
import qdrant from "./qdrant.png";
import python from "./python-logo-only.png";
import react from "./react.svg";
import github from "./github.svg";
import fastapi from "./fastapi.png";
import transformers from "./transformers.png";
import supabase from "./supabase.svg";
import bioinformatics from "./dna.svg";
import shellscript from "./shellscript.svg";
import vercel from "./vercel.svg";
import jekyll from "./jekyll.png";
export { supabase, bioinformatics, shellscript, transformers, git, postgresssql, scikitlearn, fastapi, qdrant, github, react, vercel, docker, python, jekyll };
